services:
  - type: web
    name: elearning-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/offline-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: elearning-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: elearning-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: elearning-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.netlify.app,http://localhost:3000

databases:
  - name: elearning-db
    databaseName: elearning
    user: elearning_user
    plan: free
